### ISSUE TITLE
Os desafios da comunidade.

### ISSUE THREAD

**Issue by josymarss** [Community-Dev-Angola/Joining-to-Community#10]
A comunidade tem crescendo muito e eu particularmente vejo e sigo alguns destes incríveis desenvolvedores, mas a comunidade tem de trabalhar, existem vários problemas existentes que nós como programadores temos de ir avante e resolve-los com ou sem ajuda hierárquica dos nossos dirigentes, abaixo desta issue, sugiro que os programadores desta linda comunidade deixam um comentário de um problema e a posterior solução e juntos resolvermos esse problema.

**Comment by gentildpinto** [comment]
@josymarss aprecio muito o seu ponto, por isso foi criado um [TEAM](https://github.com/orgs/Community-Dev-Angola/teams/devs-cda/discussions) onde contém todos os devs desta comunidade.
Então podes iniciar uma discussão por [Lá](https://github.com/orgs/Community-Dev-Angola/teams/devs-cda/discussions) porque acredito que quase ninguém conseguirá ver este issue :(
