### ISSUE TITLE
README.md x CONTRIBUTORS.md - Sugestões

### ISSUE THREAD

**Issue by RomarioNzenguele** [Community-Dev-Angola/Joining-to-Community#7]
De modos a evitar ao máximo falhas na interpretação das instruções para aderir a comunidade, proponho as seguintes alterações: 

- Para o README, poderia ser melhorado o ponto "5"

>  5. Adicione o seu nome de perfil e o seu nome de usuário do GitHub na seção "Membros da Organização" no arquivo CONTRIBUTORS.md

- Para o CONTRIBUTORS, poderia ser especificada a posição do nome e observada a questão da preservação das linhas existentes:

> # Join the Organization
> ## Obs: Não eliminar nenhuma linha de instrução deste ficheiro
>
> Adicione por favor o {Seu nome de perfil} e {Seu nome de usuário do GitHub} na última linha da secção "Membros da Organização" e submeta a Pull Request.
> 
> Por exemplo:
> 
> - Gentil D. Pinto [gentildpinto]
> 
> Membros da Organização:
> 
> - Kakidiako Afonso António [kakidiakoafonso]
> - Aldmiro De Jesus Passagem [aldmiropassagem]
> - Romário Nzenguele da Silva [RomarioNzenguele]

Espero ter ajudado, abraços!

**Comment by gentildpinto** [comment]
Valeu pela sua contribuição @RomarioNzenguele 🙏🏿  🎉

**Comment by RomarioNzenguele** [comment]
@gentildpinto  🙌🏾 Nada por isso
